name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: ["*"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'guizmaii/caliban'
          ref: 'ctCalibanClientsVersionedCode'
          path: 'caliban'
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Publish a local version of Caliban
        run: |
          ls -al
          cd caliban
          git config --global user.email "jules.ivanic@example.com"
          git config --global user.name "Jules Ivanic"
          git tag -a v1.2.0-SNAPSHOT-304 -m "v1.2.0-SNAPSHOT-304"
          sbt +publishM2
          cd ..
      - name: Run tests
        run: sbt clean test
