name: CI

on: [ push, pull_request ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2.3.0
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Run tests
        run: sbt clean test
