name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: ["*"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'guizmaii/caliban'
          ref: 'generate_from_code_2'
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2.3.0
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Publish a local version of Caliban
        run: |
          ls -al
          cd caliban
          sbt +publishM2
          cd ..
      - name: Run tests
        run: sbt clean test
