name: CI

on:
  push:
    branches: [main, master, series/1.x, series/2.x]
  pull_request:
    branches: ["*"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: actions/checkout@v3
#        with:
#          repository: 'guizmaii/caliban'
#          ref: 'generate_from_code_5'
#          path: 'caliban'
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
          check-latest: true
#      - name: Publish a local version of Caliban
#        run: |
#          ls -al
#          cd caliban
#          git config --global user.email "jules.ivanic@example.com"
#          git config --global user.name "Jules Ivanic"
#          git tag -a v1.1.1-SNAPSHOT-40 -m "v1.1.1-SNAPSHOT-40"
#          sbt +publishM2
#          cd ..
      - name: Run tests
        run: sbt clean test
