# This workflow will launch everyday at 00:00
on:
  schedule:
    - cron: '0 0 * * *'

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
#      - uses: actions/checkout@v2
#        with:
#          repository: 'guizmaii/caliban'
#          ref: 'generate_from_code_5'
#          path: 'caliban'
#      - uses: actions/setup-java@v2.3.0
#        with:
#          distribution: zulu
#          java-version: 11
#          check-latest: true
#      - name: Publish a local version of Caliban
#        run: |
#          ls -al
#          cd caliban
#          git config --global user.email "jules.ivanic@example.com"
#          git config --global user.name "Jules Ivanic"
#          git tag -a v1.1.1-SNAPSHOT-40 -m "v1.1.1-SNAPSHOT-40"
#          sbt +publishM2
#          cd ..
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}